name: simsiam-c100-experiment-resnet18_ifd
dataset: 
  name: seq-cifar100
  image_size: 32
  num_workers: 4

model: 
  name: simsiam
  backbone: resnet18_ifd
  cl_model: cassle
  proj_layers: 2
  buffer_size: 0
  infodrop:
    dropout_layers: 0.5
    drop_rate: 1.25
    temperature: 0.03
    band_width: 1.0
    radius: 2

train:
  optimizer: 
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.03
  final_lr: 0
  num_epochs: 200 # this parameter influence the lr decay
  stop_at_epoch: 200 # has to be smaller than num_epochs
  batch_size: 256
  knn_monitor: True # knn monitor will take more time
  knn_k: 200
  alpha: 1.0
  lambda_info: 0.1

seed: null # None type for yaml file
# two things might lead to stochastic behavior other than seed:
# worker_init_fn from dataloader and torch.nn.functional.interpolate 
# (keep this in mind if you want to achieve 100% deterministic)